### ISSUE TITLE
Input Shaper

### ISSUE THREAD

**Issue by pganns** [QIDITECH/QIDI_PLUS3#13]
Evaluate the possibility of creating macros that allow graphical visualization of the results of the Input Shaper algorithms.

**Comment by CChen616** [comment]
Due to the current limitations in screen resolution and transmission rates, it is challenging to integrate this feature directly into the screen interface. However, you can manually generate and view the images by following these steps:

1. SSH into the printer's system.

2. Run the script using Python3 and specify the output directory:
```py
python3 /home/mks/klipper/scripts/graph_shaper.py -o [destination folder]
```
For example:
```py
python3 /home/mks/klipper/scripts/graph_shaper.py -o /home/mks/klipper/scripts/
```
3. Afterwards, you can find the **.png** file, which is the image you want, in the specified folder.
