### ISSUE TITLE
Code for new releases not available

### ISSUE THREAD

**Issue by stew675** [QIDITECH/QIDI_PLUS3#3]
I noticed that for the last few releases that the source code base hasn't been updated other than updates to the README.md file

Is it possible to have the source code changes for the latest releases be pushed to the repositories?

**Comment by Rainboooom** [comment]
![image](https://github.com/QIDITECH/QIDI_PLUS3/assets/131979403/324d1dbf-a05b-4018-9e69-8a84c4bdaf0a)
Because we want everyone to have a direct view of the upgrade files and necessary processes you need at first glance, I synchronized the latest version of the main branch's read.me file. If you need to see the latest version of the source code, just switch to the corresponding branch in the upper left corner.

**Comment by stew675** [comment]
Ah, thank you for that.  I'm generally familiar with the default branch also being synced with the latest release branches.
